name: CI/CD Test Automation

on:
  pull_request:
    branches: [develop]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v1

      - name: Install node modules
        run: |
          yarn Install

      - name: Run test
        run: |
          yarn test
