name: CI/CD Test Automation

on:
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Post test results to PR
      uses: actions/github-script@v4
      if: always()
      with:
        script: |
          const fs = require('fs');
          const testResults = fs.readFileSync('./path-to-your-test-results', {encoding: 'utf8'});
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Test Results:\n${testResults}`
          });
